export const FETCH_FREE_WEEK_START = 'FETCH_FREE_WEEK_START';
export const FETCH_FREE_WEEK_SUCCESS = 'FETCH_FREE_WEEK_SUCCESS';
export const FETCH_FREE_WEEK_FAIL = 'FETCH_FREE_WEEK_FAIL';

export const FETCH_PROMOTIONS_START = 'FETCH_PROMOTIONS_START';
export const FETCH_PROMOTIONS_SUCCESS = 'FETCH_PROMOTIONS_SUCCESS';
export const FETCH_PROMOTIONS_FAIL = 'FETCH_PROMOTIONS_FAIL';